version: '2'
services:
    web:
        build: .
        user: "node"
        working_dir: /home/node/app
        environment:
            - NODE_ENV=production
        volumes:
            - ./:/home/node/app
        ports:
            - 8080
        command: "npm start"